### ISSUE TITLE
User always null

### ISSUE THREAD

**Issue by brianbellini** [micahwierenga/sei-cc-7-project-4-issues#1]
After creating a user, the token encoding seems to be working but I'm either not getting the token returned from the server or my code sucks.

```
function getUserFromToken() {
    const token = getToken();
    return token ? JSON.parse(atob(token.split('.')[1])).user : null;
}
```

I'm not getting any error codes and both the working and production builds are running fine.
The DB seems to be storing a hashed password so that seems to be ok.  Tried console logging but can't seem to track down where the issue is happening and now my head hurts too much.

**Comment by micahwierenga** [comment]
`dotenv` was loading before the routes, thus rendering the `SECRET` as undefined.
