### ISSUE TITLE
I just need a battle plan, help with everything, I am NOWHERE near deployment ready

### ISSUE THREAD

**Issue by DagnyJay** [micahwierenga/sei-cc-7-project-4-issues#11]
title says it all - sorry to be vague but I am not getting this and I am putting the work/hours in. I need a plan to be deployment ready by tomorrow, whatever that means and whatever that looks like

**Comment by micahwierenga** [comment]
1. Create utils/wordService.js
2. Stub up a function called getRandomWords (make sure to include "export" in front of "function")
3. Inside this function, create a fetch request to the api (put "return" in front of the fetch request) (use dogAPI in Puppies app as example)
4. Inside App.js, import wordService
5. Inside App.js, create a function called handleGetRandomWords
6. Inside this function, make a call to wordService.getRandomWords (store this call in a variable; make sure the function is async and the call to the service is await)
7. Call handleGetRandomWords from componentDidMount
8. Test by console.logging your variable (inside handleGetRandomWords)
9. If you're getting data, set it to a state variable called randomWords (inside handleGetRandomWords)
10. Pass this.state.randomWords to RandomWordPrompts
11. Pass individual words from this array into each RandomWordPrompt
12. Inside RandomWordPrompt, display the word that was passed to it. (edited)
