### ISSUE TITLE
Recap/plan how to get user reference into Shortcut model and create a favorite list.

### ISSUE THREAD

**Issue by brianbellini** [micahwierenga/sei-cc-7-project-4-issues#13]
Got the basic functions with the 'Master' shortcut list working.  Want to brain storm best plan of attack for favorite shortcut list.  Also, unsure of the best way to reference a 'creator' for the master shortcuts vs the user added shortcuts.

**Comment by micahwierenga** [comment]
Discussed creating new MyList model and just duplicating master shortcuts when a user favorites a shortcut.
