### ISSUE TITLE
Critical Dependency Error

### ISSUE THREAD

**Issue by rjohnson0707** [micahwierenga/sei-cc-7-project-4-issues#2]
When I try to run localhost:3000, my terminal is spitting out 
"Critical dependency: the request of a dependency is an expression"

on LH:3000 it is telling me 
"TypeError: Cannot read property 'prototype' of undefined"
        the error is in node_modules/express/lib/response.js:42
(`var res = Object.create(http.ServerResponse.prototype)`)

**Comment by micahwierenga** [comment]
The `HomePage` component wasn't rendering any jsx and wasn't being exported.
