### ISSUE TITLE
Getting a 500 error when posting data

### ISSUE THREAD

**Issue by brianbellini** [micahwierenga/sei-cc-7-project-4-issues#20]
The error is pointing to the second line of this function:

`
export function create(shortcut) {
    return fetch(BASE_URL, {
        method: 'POST',
        headers: {
          'Content-type': 'application/json',
          'Authorization': `Bearer ${tokenService.getToken()}`
        },
        body: JSON.stringify(shortcut)
    }).then(res => res.json());
}
`

**Comment by micahwierenga** [comment]
Refactored back-end `create` controller to access user to save embedded docs.
