### ISSUE TITLE
WritingsList page is getting passed "writings", but won't map them

### ISSUE THREAD

**Issue by DagnyJay** [micahwierenga/sei-cc-7-project-4-issues#22]
My WritingsPage virtually mimics the PuppyListPage, and I feel good about the logic from App.js being passed down, but I get this error when I try to map:

![](https://files.slack.com/files-pri/T0351JZQ0-F011Z2EUDE1/screen_shot_2020-04-16_at_7.24.43_pm.png)

Tyler and I tried putting this one to rest for an hour yesterday with no luck. Any help is appreciated! The page just won't render

**Comment by micahwierenga** [comment]
Set `writings` in state to initialize to an empty array.
