### ISSUE TITLE
Submit data from one document to another, Delete got broken, Edit shortcut

### ISSUE THREAD

**Issue by brianbellini** [micahwierenga/sei-cc-7-project-4-issues#23]
Had to refactor some stuff while working with Tyler last night and my delete functionality has me confused now that the shortcuts are nested inside the user.

Want to check I'm using the best method to Edit a shortcut.

Unsure how to send a shortcut from my master list into the user myList schema.

**Comment by micahwierenga** [comment]
Updated deleteOne controller to use mongoose `$pull` feature.
