### ISSUE TITLE
Implement copy shortcut to myList

### ISSUE THREAD

**Issue by brianbellini** [micahwierenga/sei-cc-7-project-4-issues#27]
I forgot to ask you about this earlier.
I'm also getting an error that I thought we fixed when I'm editing.  It happened when we tried to use componentDidUpdate before and started a loop, now it seems to be happening with edit.
I also need to refresh after deleting, I'm removing from the database but the shortcut stays in the table.

**Comment by micahwierenga** [comment]
Due to the fact that the `user` document was being altered, a new token needed to be generated for each manipulation of the `myList` array.
