### ISSUE TITLE
Styling help - how to make components display on a page in what order

### ISSUE THREAD

**Issue by DagnyJay** [micahwierenga/sei-cc-7-project-4-issues#6]
Prolly a repeat of Jacob's questions, but I am just trying to make my navbar resemble that in the puppies app, and I cannot make it do what I want. It's so basic I just want an overview before I bang my head against this more.

**Comment by micahwierenga** [comment]
Moved NavBar rendering to App.js for persistence across app. And, put it inside header element to take advantage of the flex styles already applied.
